name: event-triggers-example
on:
  push:
    branches:
      - "master"
      - '!foo/*/456'
    tags:
      - "*"
  schedule:
    - cron: '*/15 * * * *'
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      -
        name: Event
        run: "Triggered by: $GITHUB_EVENT_NAME"
      -
        name: Say Hello
        run: echo "Hello world!"